### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by philclifford** [ymauray/deborah#1]
Don't know whose bug it is but my extensive collection of deb-get installed toys has one showing an update in `deborah`. Only problem is it is up to date and trying update the app button or refresh button just ends up with one avaialable update showing.
![2022-07-25_03-23-deborahbug](https://user-images.githubusercontent.com/8797027/180681450-5884084d-c08d-432c-bbd1-3eed79cc9182.png)

**Comment by philclifford** [comment]
to be sure, `deb-get update`gives (minus the apt outputs)

```
  [+] Updating /var/cache/deb-get/balena-etcher-electron.json
  [+] Updating /var/cache/deb-get/bat.json
  [+] Updating /var/cache/deb-get/deb-get.json
  [+] Updating /var/cache/deb-get/duf.json
  [+] Updating /var/cache/deb-get/fd.json
  [+] Updating /var/cache/deb-get/flameshot.json
  [+] Updating /var/cache/deb-get/gh.json
  [+] Updating /var/cache/deb-get/git-delta.json
  [+] Updating /var/cache/deb-get/hugo.json
  [+] Updating /var/cache/deb-get/lsd.json
  [+] Updating /var/cache/deb-get/obs-cli.json
  [+] Updating /var/cache/deb-get/obsidian.json
  [+] Updating /var/cache/deb-get/pandoc.json
  [+] Updating /var/cache/deb-get/trivy.json
  [+] Updating /var/cache/deb-get/zenith.json
```

**Comment by ymauray** [comment]
Thanks for the report. The updates part is not working very well right now. That should be fixed in the upcoming beta version.

**Comment by philclifford** [comment]
You're welcome. Closing and awaiting beta with interest.
