### ISSUE TITLE
New Feature not quite working here

### ISSUE THREAD

**Issue by philclifford** [ymauray/deborah#11]
I have my API token set but the lovely new up-front warning still appears. But when I go to "Options" that page knows I have the token set and gives the appropriate confirmation.  Is there a typo somewhere ....
If I unset the DEBGET_TOKEN My Apps page has no warning, but there is a warning and switch on the "Options" page

**Comment by ymauray** [comment]
Yeah... That's me being tired :-) To test the feature, I inverted the test, and guess what ... I forgot to revert it :-)

Well, I guess that will be for 1.0.3-beta tomorrow ! 

Thanks as usual for being my reviewer !

**Comment by philclifford** [comment]
My pleasure! Have a great weekend.

**Comment by philclifford** [comment]
Just closed the  second testing deborah (clicking (X )) I ran from a shell without a token and got a warning out to the calling shell (probably nothing but in case ,..)

```
(deborah:557187): GLib-GObject-WARNING **: 00:29:48.619: ../../../gobject/gsignal.c:2731: instance '0x56185137f1b0' has no handler with id '109'
```
:shrug:
