### ISSUE TITLE
GLIBC 2.34 not found

### ISSUE THREAD

**Issue by Neocamelus** [ymauray/deborah#21]
With Ubuntu Focal Fossa, I have the following error message:
 /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by deborah)
 
I can only have a 2.31 version :cry:

**Comment by ymauray** [comment]
Hello, thanks for raising this issue. This probably means I need to build the app in a Focal VM. I shall do that as soon as I have time !

**Comment by ymauray** [comment]
I'm now building the app in a 20.04 systemd container, that should fix the GLIBC version problem. I'll leave this issue opened until you can confirm it works for you starting from the 1.1.3 release.

**Comment by Neocamelus** [comment]
With the new version of Deborah, the problem is no longer present. Thanks a lot!
