### ISSUE TITLE
Installing a package doesn't reflect in the current status of that package immediately

### ISSUE THREAD

**Issue by thelovebug** [ymauray/deborah#22]
# Steps to reproduce

## Installing a package

* Search or scroll for a package that isn't already installed
* Click the [Install] button, and authenticate
* Package installs, as evidenced in the status bar at the bottom.
* [Install] button remains, no tick in the third column, and the version number doesn't appear under the package name, until...
* Press the [Refresh] button
* [Install] button immediately becomes [Remove], the tick appears in the third column, and the version number appears under the package name
* Package list gets refreshed

## Uninstalling a package

* Exactly the same as the above, but the opposite way around

# What should happen

* Once the package has been installed or removed:
  * the [Install]/[Remove] button should change accordingly
  * the tick in the third column should appear/disappear accordingly
  * the version number under the package name should appear/disappear accordingly

**Comment by ymauray** [comment]
Thanks for the feedback, I will have a look at that.
