### ISSUE TITLE
A Few minor comments

### ISSUE THREAD

**Issue by philclifford** [ymauray/deborah#6]
- [ ] An option to show "only not installed" might be nice.

- [x] "softwares" isn't vraimant idomatique en englais.  Software packages (or applications ) would be better, but would take up a lot of space so I'd suggest packages or applications.

- [x] If you have no API PAT set it might be nice to have a little indicator on the main screen that takes you to the "settings" explanation, and maybe an option there to turn off the beacon/indicator on the main screen.  Otherwise many people will not look at settings, or the discord or github etc, will install lots of toys and then complain about errors on twitter ....

- [x] If you `deb-get update` outside of deborah the "updatable" apps in deborah are outdated.  Even if you click "Check for Updates" they remain showing the outdated set unless you uncheck then re-check "show only upgradable apps"  I wonder if some "refresh" trigger could be implemented easily if the cached information becomes outdated. 

- [x] Can the search function be (optionally) case-insensitive ?

- [x] If you have extra used-defined functions in place the gentle prompt appears in the "show" information e.g. for updates.  This is probably a good thing, but is it possible to either respect/refactor the ANSI codes or strip them?  

![image](https://user-images.githubusercontent.com/8797027/190450616-f455364e-c34f-4455-b6e3-400900d73a1f.png)

**Comment by ymauray** [comment]
Thanks for the comments ! I will take actions ASAP. How about "Apps" instead of software or application ? Nowadays, everything is an app.

**Comment by philclifford** [comment]
You're very welcome!   Just a few little things that might be worth a little effort.  Nothing that should hold up a release or spoil a weekend!

Apps is fine (and is consistent with other places in the UI)

Just noticed that the URLs in the drop-down "show" panels are not clickable, nor can you select/copy or right-click them.  It would be nice to be able to do one and/or the other (otherwise the shell beats the gui again :stuck_out_tongue:  )

**Comment by philclifford** [comment]
One more tiny suggestion: if there were some indicator for "installed" in the main list it would help .

**Comment by philclifford** [comment]
Ohhh  TIL if you make lists checklists in issues you get a "convert to issue" button !
(Don't think any of these are worthy of an issue themselves - just thought some tick boxes might help (if you can check them) )
