### ISSUE TITLE
Package details do not update when searching

### ISSUE THREAD

**Issue by natanjunges** [ymauray/deborah#7]
When doing multiple searches, the details of the packages loaded in the previous ones are shown, instead of loading the correct details for the packages in the current search (closing and reopening `deborah` fixes it). For example, if I search for `cod`, the results are:
- Visual Studio Code
- VSCodium
- shutter-encoder

If I expand their details, as this is the first search, they will load correctly. If afterwards I search for `vpn`, the results are:
- Expressvpn
- Mullvad VPN Client
- NordVPN
- Proton VPN

But, as this is not the first search, if I expand their details, for three of those results (the number of package details loaded in previous searches), they will show the details of the previous searches, which returned totally different packages, and for the one remaining package, it will load its details correctly. In my case, those were the details shown, but they depend on the order the packages' details are expanded:
- Expressvpn: shown details of Visual Studio Code
- Mullvad VPN Client: shown details of VSCodium
- NordVPN: shown details of shutter-encoder
- Proton VPN: shown correctly details of itself

**Comment by philclifford** [comment]
Also resets/refreshes if you toggle "Only show installed apps:"  (and here after doing that expanded details of "vpn" search are correct, as are "cod" if you re-search that BUT if you search "Kanb" it shows Brisqi with details from Expressvpn)

**Comment by philclifford** [comment]
Similar if you toggle "Only show upgradable apps" - you get loading and then Brisqi will be right (and cod and vpn results) BUT if you search "lif" then you get two results: expanding Rambox has the right details but (given what I have/had expanded previously) I get Standard Notes with the "show" from Mullvad VPN Client

Seems that previously expanded results are cached and the array re-used so e.g. prior  opened list[1] and list[3] results show wrong details but if you expand list[2] you get "loading" then the correct details.

Caching is better than not obv. but some connections or separations or dimensions need a tweak.
